### ISSUE TITLE
Better jump to definition in jarfiles.

### ISSUE THREAD

**Issue by snoe** [snoe/clojure-lsp#27]
Currently when trying to get the definition of something defined in a jar file we return a pseudo uri for zipfiles that vim understands but no one else does.

`zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar::clojure/core.clj`

Let's figure out what servers do for java and see if we can use that instead. (They might use a `jdt` protocol uri). Most clients I've seen have special handling for something in the java lsp server which I think is related to this problem.

https://github.com/neoclide/coc.nvim/issues/652

**Comment by snoe** [comment]
Should be fixed with 
24ebfa6f591e1f8bb80aac191c6adb635497bf77  and
7bc1fb3d1b4a5535362420fc67bc4a90f5731d01 which has an example of a client handling the IANA `jar` scheme.

**Comment by benedekfazekas** [comment]
trying to make this work with emacs.

I put a `.lsp/config.edn` in the project like:
```
{"dependency-scheme" "jar"}
```

still getting back an uri starting with `zipfile:///...`

what am i doing wrong?

**Comment by snoe** [comment]
ah, rm the `.lsp/sqlite.1.db` in your project

**Comment by benedekfazekas** [comment]
yup, the right uri comes back now. cheers

**Comment by benedekfazekas** [comment]
still on the emacs side of things.

I figured I need an `uri-handler` to make jumping into source work for dependencies (jarred up obviously) I put together something rather hacky and it works :).

if I ever clean that up this should go into https://github.com/emacs-lsp/lsp-mode probably in a separate lsp-clojure.el file. Does this sound right @snoe ?

this starting to feel amazing btw :) thanks for the whole thing!!

**Comment by snoe** [comment]
Yeah, that sounds about right, it'd be great to get it distributed with lsp-mode
